# Site
title: Cli
subtitle: ""
description: ""
keywords:
author: Test
language: en
timezone: ""

url: https://mobile-ekko.github.io/docs.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# favicon
theme_config:
  favicon: images/favicon.ico

theme: doc

# Writing
new_post_name: :title.md # File name of new posts
